### ISSUE TITLE
How to use this code

### ISSUE THREAD

**Issue by TamerElsherif** [husam287/shein-webscrapping#1]
Hi Hussam,
could please show basic steps of how to use this code 

thanks a lot in advance :)

**Comment by husam287** [comment]
@TamerElsherif  I'll provide the readme file with all the details ASAP

**Comment by TamerElsherif** [comment]
Thanks you Hussam. awaiting for it

**Comment by husam287** [comment]
You can check now @TamerElsherif

**Comment by TamerElsherif** [comment]
Great. Thanks a lot Hussam
